// example/svelte/src/ExampleMultiSelect.svelte
<script lang="ts">
  import * as Combobox from "./src";

  /*


  Step 0: Have some data


  */

  type Item = { id: number; label: string };
  const fruits: Item[] = [
    { id: 0, label: "pear" },
    { id: 1, label: "apple" },
    { id: 2, label: "banana" },
    { id: 3, label: "orange" },
    { id: 4, label: "strawberry" },
    { id: 5, label: "kiwi" },
    { id: 6, label: "mango" },
    { id: 7, label: "pineapple" },
    { id: 8, label: "watermelon" },
    { id: 9, label: "grape" },
  ];

  let selectedItems: { [itemId: string]: HTMLElement } = {};
  let items: { [itemId: string]: HTMLElement } = {};
  let input: HTMLInputElement | null = null;

  /*


  Step 1: Init the config


  */

  const config = Combobox.initConfig<Item>({
    toItemId: (item) => item.id,
    toItemInputValue: (item) => item.label,
  });

  /*


  Step 2: Init the state


  */

  let model = Combobox.init({
    allItems: fruits,
    mode: { type: "multi-select" },
  });

  /*


  Step 3: Write some glue code


  */

  const dispatch = (msg: Combobox.Msg<Item>) => {
    const output = Combobox.update(config, { msg, model });

    model = output.model;

    Combobox.runEffects(output, {
      focusSelectedItem: (selectedItem) => {
        selectedItems[selectedItem.id]?.focus();
      },
      focusInput: () => {
        input?.focus();
      },
      scrollItemIntoView: (item) => {
        items[item.id]?.scrollIntoView({ block: "nearest" });
      },
    });

    console.log(msg.type, output.model.type);
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    const msg = Combobox.browserKeyboardEventKeyToMsg<Item>(event.key);
    if (msg.shouldPreventDefault) {
      event.preventDefault();
    }
    dispatch(msg);
  };

  /*


  Step 3: Wire up to the UI


  */

  $: state = Combobox.toState(config, model);
</script>

<div>
  <label
    class="label"
    {...state.aria.inputLabel}
    for={state.aria.inputLabel.for}
  >
    Fruit Multi Select
  </label>

  <div class="input-container" on:keydown={handleKeyDown}>
    <p {...state.aria.helperText}>
      {Combobox.ariaContentDefaults.helperText}
    </p>

    <ul class="chip-list" {...state.aria.selectedList}>
      {#each state.selections as selectedItem}
        <li
          {...state.aria.selectedItem(selectedItem)}
          bind:this={selectedItems[selectedItem.id]}
          class="chip"
          class:chip-highlighted={state.isSelectedItemFocused(selectedItem)}
          on:focus={() =>
            dispatch({ type: "focused-selected-item", item: selectedItem })}
        >
          {selectedItem.label}
          <span
            {...state.aria.unselectButton(selectedItem)}
            class="chip-delete-btn"
            on:mousedown|preventDefault={() =>
              dispatch({ type: "pressed-unselect-button", item: selectedItem })}
          >
            &times;
          </span>
        </li>
      {/each}
    </ul>

    <input
      {...state.aria.input}
      class="input"
      value={state.inputValue}
      bind:this={input}
      on:input={(event) =>
        dispatch({
          type: "inputted-value",
          inputValue: event.currentTarget.value,
        })}
      on:click={() => dispatch({ type: "pressed-input" })}
      on:focus={() => dispatch({ type: "focused-input" })}
      on:blur={() => dispatch({ type: "blurred-input" })}
    />
    <ul
      {...state.aria.itemList}
      class="suggestions"
      class:hide={!state.isOpened}
    >
      {#if state.items.length === 0}
        <li>No results</li>
      {/if}
      {#each state.items as item, index}
        <li
          {...state.aria.item(item)}
          bind:this={items[item.id]}
          on:mousemove={() => dispatch({ type: "hovered-over-item", index })}
          on:mousedown|preventDefault={() =>
            dispatch({ type: "pressed-item", item })}
          on:focus={() => dispatch({ type: "hovered-over-item", index })}
          class="option"
          class:highlighted={state.itemStatus(item) === "highlighted"}
          class:selected={state.itemStatus(item) === "selected"}
          class:selected-and-highlighted={state.itemStatus(item) ===
            "selected-and-highlighted"}
        >
          {config.toItemInputValue(item)}
        </li>
      {/each}
    </ul>
  </div>
</div>

<style>
  .input-container {
    position: relative;
    width: 100%;
    max-width: 300px;
  }

  .label {
    position: relative;
    display: block;
    width: 100%;
    margin: auto;
  }

  .hide {
    display: none;
  }
  .input {
    width: 100%;

    font-size: large;
    padding: 0.5rem;
    box-sizing: border-box;
    border: 1px solid #ccc;
  }
  .suggestions {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    z-index: 1;
    width: 100%;
    max-height: 200px;
    overflow: scroll;
    border: 1px solid #ccc;
    width: 100%;
    max-width: 100%;
    margin: 0;
    padding: 0;
    background: #efefef;
  }

  @media (prefers-color-scheme: dark) {
    .suggestions {
      background: #121212;
    }
  }

  .option {
    display: block;
    cursor: pointer;
    list-style: none;
    width: 100%;
    font-size: large;
    margin: 0;
    padding: 0;
  }

  .highlighted {
    background-color: #333;
    color: white;
  }

  @media (prefers-color-scheme: dark) {
    .highlighted {
      background-color: #eee;
      color: black;
    }
  }

  .selected {
    background-color: blue;
    color: white;
  }
  .selected-and-highlighted {
    background-color: lightblue;
  }

  .chip-list {
    display: flex;
    flex-direction: row-reverse;
    flex-wrap: wrap-reverse;
  }
  .chip {
    display: flex;
    align-items: center;
    padding: 0.5rem;
    margin: 0.5rem;
    gap: 0.5rem;
    background: #efefef;
    border-radius: 0.5rem;
    height: 1.5rem;
    cursor: default;
    font-size: large;
  }
  .chip-highlighted {
    background: #333;
    color: white;
  }

  .chip-delete-btn {
    font-size: medium;
    background: transparent;
    padding: 4px;
    border-radius: 100%;
    cursor: pointer;
  }

  @media (prefers-color-scheme: dark) {
    .chip {
      background: #121212;
    }
  }
</style>

// example/react-native-example/ExampleMultiSelect.tsx
import { useRef, useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import * as Combobox from "./src";

/*


  Step 0: Have some data


  */

type Item = { id: number; label: string };
const fruits: Item[] = [
  { id: 0, label: "pear" },
  { id: 1, label: "apple" },
  { id: 2, label: "banana" },
  { id: 3, label: "orange" },
  { id: 4, label: "strawberry" },
  { id: 5, label: "kiwi" },
  { id: 6, label: "mango" },
  { id: 7, label: "pineapple" },
  { id: 8, label: "watermelon" },
  { id: 9, label: "grape" },
];

/*


  Step 1: Init the config


  */

const config = Combobox.initConfig<Item>({
  toItemId: (item) => item.id,
  toItemInputValue: (item) => item.label,
});

export default function ExampleMultiSelect() {
  const [model, setModel] = useState(
    Combobox.init<Item>({
      allItems: fruits,
      mode: {
        type: "multi-select",
        selectedItemsDirection: "right-to-left",
      },
    })
  );

  const inputRef = useRef<TextInput | null>(null);
  const scrollViewRef = useRef<ScrollView | null>(null);
  const [itemY, setItemY] = useState<{ [itemId: string]: number }>({});

  /*


  Step 3: Write some glue code


  */

  const dispatch = (msg: Combobox.Msg<Item>) => {
    const output = Combobox.update(config, { msg, model });

    setModel(output.model);

    Combobox.runEffects(output, {
      focusSelectedItem: (_selectedItem) => {
        //
      },
      focusInput: () => {
        inputRef.current?.focus();
      },
      scrollItemIntoView: (item) => {
        const y = itemY[item.id];
        const scrollView = scrollViewRef.current;
        if (y && scrollView) {
          scrollView.scrollTo({ y, animated: true });
        }
      },
    });

    console.log(msg, output.model.type);
  };

  const state = Combobox.toState(config, model);
  return (
    <View style={styles.container}>
      <View style={styles.inputContainer}>
        <View style={styles.chipContainer}>
          {state.selections.map((item) => (
            <View
              key={item.id}
              style={{
                ...styles.chip,
                ...(state.isSelectedItemFocused(item)
                  ? styles.chipFocused
                  : {}),
              }}>
              <Text style={{ color: "inherit" }}>{item.label}</Text>
            </View>
          ))}
        </View>

        <TextInput
          style={styles.input}
          placeholder="Search fruits"
          value={state.inputValue}
          onFocus={() => dispatch({ type: "focused-input" })}
          onBlur={() => dispatch({ type: "blurred-input" })}
          onTouchStart={() => dispatch({ type: "pressed-input" })}
          ref={inputRef}
          onKeyPress={(e) => {
            const key = e.nativeEvent.key;
            const msg = Combobox.keyToMsg<Item>(key);
            if (msg.shouldPreventDefault) {
              e.preventDefault();
            }
            dispatch(msg);
          }}
          onChangeText={(text) =>
            dispatch({ type: "inputted-value", inputValue: text })
          }
        />

        {state.isOpened && (
          <ScrollView style={styles.suggestionList} ref={scrollViewRef}>
            {state.items.map((item) => (
              <View
                onLayout={(e) => {
                  const y = e?.nativeEvent?.layout?.y;
                  if (typeof y === "number") {
                    setItemY((itemY) => ({ ...itemY, [item.id]: y }));
                  }
                }}
                onTouchStart={() => dispatch({ type: "pressed-item", item })}
                style={{
                  ...styles.suggestionListItem,
                  ...(state.itemStatus(item) === "highlighted"
                    ? { backgroundColor: "#ccc" }
                    : state.itemStatus(item) === "selected"
                    ? styles.suggestionListItemSelected
                    : state.itemStatus(item) === "selected-and-highlighted"
                    ? { backgroundColor: "lightblue" }
                    : { backgroundColor: "transparent" }),
                }}
                key={item.id}>
                <Text style={{ color: "inherit" }}>{item.label}</Text>
              </View>
            ))}
          </ScrollView>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  input: {
    width: "100%",
    fontSize: 20,
  },
  inputContainer: {
    width: "100%",
    padding: 10,
    border: "1px solid #ccc",
    position: "relative",
  },
  suggestionList: {
    width: "100%",
    border: "1px solid #ccc",
    position: "absolute",
    top: "100%",
    left: 0,
    // height: 200,
    overflow: "scroll",
  },
  suggestionListItem: {
    padding: 10,
  },
  suggestionListItemSelected: {
    backgroundColor: "blue",
    color: "#fff",
  },
  chipContainer: {
    // flexDirection: "row",
    // flexWrap: "wrap",
    justifyContent: "flex-end",
    flexDirection: "row-reverse",
    flexWrap: "wrap-reverse",
  },
  chip: {
    padding: 5,
    margin: 5,
    backgroundColor: "#eee",
    borderRadius: 5,
    fontSize: 16,
  },
  chipFocused: {
    backgroundColor: "blue",
    color: "#fff",
  },
});
